#!/bin/bash

# TWRP Device Information Extraction Script
# This script extracts all necessary information from an Android device via ADB
# for building TWRP recovery

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored output
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "\n${GREEN}=== $1 ===${NC}\n"
}

# Check if ADB is installed
if ! command -v adb &> /dev/null; then
    print_error "ADB is not installed or not in PATH"
    echo "Please install Android SDK Platform Tools"
    echo "Download from: https://developer.android.com/studio/releases/platform-tools"
    exit 1
fi

print_header "TWRP Device Information Extraction Tool"
print_info "This script will extract device information needed for TWRP building"

# Check if device is connected
print_info "Checking for connected devices..."
if ! adb devices | grep -q "device$"; then
    print_error "No device connected or device not authorized"
    echo ""
    echo "Please ensure:"
    echo "  1. USB Debugging is enabled on your device"
    echo "  2. Device is connected via USB"
    echo "  3. You have authorized ADB on the device"
    echo ""
    echo "Run 'adb devices' to verify connection"
    exit 1
fi

print_success "Device connected"

# Get device codename for filename
CODENAME=$(adb shell getprop ro.product.device 2>/dev/null | tr -d '\r\n')
if [ -z "$CODENAME" ]; then
    CODENAME="unknown"
fi

OUTPUT_FILE="device_info_${CODENAME}.txt"

print_info "Output will be saved to: $OUTPUT_FILE"
print_info "Starting information extraction..."

# Create output file with header
{
    echo "========================================"
    echo "  TWRP DEVICE INFORMATION REPORT"
    echo "========================================"
    echo "Generated on: $(date)"
    echo "Generated by: TWRP Device Info Extraction Script"
    echo "========================================"
    echo ""
} > "$OUTPUT_FILE"

# Function to safely get property
get_prop() {
    adb shell getprop "$1" 2>/dev/null | tr -d '\r\n' || echo "N/A"
}

# Function to safely execute command
safe_exec() {
    adb shell "$1" 2>/dev/null | tr -d '\r' || echo "N/A"
}

# Basic Device Information
print_header "Basic Device Information"
{
    echo "--- BASIC DEVICE INFORMATION ---"
    echo "Device Codename: $(get_prop ro.product.device)"
    echo "Product Name: $(get_prop ro.product.name)"
    echo "Brand: $(get_prop ro.product.brand)"
    echo "Model: $(get_prop ro.product.model)"
    echo "Manufacturer: $(get_prop ro.product.manufacturer)"
    echo "Board: $(get_prop ro.product.board)"
    echo "Hardware: $(get_prop ro.hardware)"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Android Version Information
print_header "Android Version Information"
{
    echo "--- ANDROID VERSION INFORMATION ---"
    echo "Android Version: $(get_prop ro.build.version.release)"
    echo "API Level: $(get_prop ro.build.version.sdk)"
    echo "Build ID: $(get_prop ro.build.id)"
    echo "Build Type: $(get_prop ro.build.type)"
    echo "Build Tags: $(get_prop ro.build.tags)"
    echo "Build Date: $(get_prop ro.build.date)"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Architecture Information
print_header "Architecture Information"
{
    echo "--- ARCHITECTURE INFORMATION ---"
    echo "Primary ABI: $(get_prop ro.product.cpu.abi)"
    echo "Secondary ABI: $(get_prop ro.product.cpu.abi2)"
    echo "Supported ABIs: $(get_prop ro.product.cpu.abilist)"
    echo "Supported 32-bit ABIs: $(get_prop ro.product.cpu.abilist32)"
    echo "Supported 64-bit ABIs: $(get_prop ro.product.cpu.abilist64)"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Platform Information
print_header "Platform Information"
{
    echo "--- PLATFORM INFORMATION ---"
    echo "Board Platform: $(get_prop ro.board.platform)"
    echo "Hardware Platform: $(get_prop ro.hardware.platform)"
    echo "Chipset: $(get_prop ro.chipname)"
    echo "SoC Manufacturer: $(get_prop ro.soc.manufacturer)"
    echo "SoC Model: $(get_prop ro.soc.model)"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Kernel Information
print_header "Kernel Information"
{
    echo "--- KERNEL INFORMATION ---"
    echo "Kernel Version:"
    safe_exec "cat /proc/version"
    echo ""
    echo "Kernel Command Line:"
    safe_exec "cat /proc/cmdline"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Bootloader Information
print_header "Bootloader Information"
{
    echo "--- BOOTLOADER INFORMATION ---"
    echo "Bootloader Version: $(get_prop ro.bootloader)"
    echo "Baseband Version: $(get_prop ro.baseband)"
    echo "Radio Version: $(get_prop gsm.version.baseband)"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Display Information
print_header "Display Information"
{
    echo "--- DISPLAY INFORMATION ---"
    echo "Screen Resolution:"
    safe_exec "wm size"
    echo ""
    echo "Screen Density:"
    safe_exec "wm density"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Partition Information
print_header "Partition Information"
{
    echo "--- PARTITION INFORMATION ---"
    echo "Partitions (from /proc/partitions):"
    safe_exec "cat /proc/partitions"
    echo ""
    echo "Block Device Names:"
    # Try multiple common paths sequentially
    if ! safe_exec "ls -la /dev/block/platform/*/by-name/" | grep -q "^l"; then
        if ! safe_exec "ls -la /dev/block/bootdevice/by-name/" | grep -q "^l"; then
            echo "Could not find by-name directory"
        fi
    fi
    echo ""
} | tee -a "$OUTPUT_FILE"

# Storage Information
print_header "Storage Information"
{
    echo "--- STORAGE INFORMATION ---"
    echo "Disk Usage:"
    safe_exec "df -h"
    echo ""
    echo "Mount Points:"
    safe_exec "mount"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Build Fingerprint
print_header "Build Information"
{
    echo "--- BUILD INFORMATION ---"
    echo "Build Fingerprint: $(get_prop ro.build.fingerprint)"
    echo "Build Description: $(get_prop ro.build.description)"
    echo "Build Host: $(get_prop ro.build.host)"
    echo "Build User: $(get_prop ro.build.user)"
    echo ""
} | tee -a "$OUTPUT_FILE"

# SELinux Information
print_header "SELinux Information"
{
    echo "--- SELINUX INFORMATION ---"
    echo "SELinux Status:"
    safe_exec "getenforce"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Fstab Information (if accessible)
print_header "Fstab Information"
{
    echo "--- FSTAB INFORMATION ---"
    echo "Attempting to read fstab files..."
    echo ""
    
    echo "Recovery fstab (if exists):"
    safe_exec "cat /etc/recovery.fstab 2>/dev/null || echo 'Not accessible'"
    echo ""
    
    echo "TWRP fstab (if exists):"
    safe_exec "cat /etc/twrp.fstab 2>/dev/null || echo 'Not accessible'"
    echo ""
    
    echo "System fstab files:"
    safe_exec "ls -la /system/etc/fstab* /vendor/etc/fstab* 2>/dev/null || echo 'Not accessible'"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Summary for TWRP Building
print_header "TWRP Building Summary"
{
    echo "--- TWRP BUILDING QUICK REFERENCE ---"
    echo ""
    echo "For BoardConfig.mk:"
    echo "  TARGET_BOARD_PLATFORM := $(get_prop ro.board.platform)"
    echo "  TARGET_ARCH := $(get_prop ro.product.cpu.abi | cut -d'-' -f1)"
    echo ""
    echo "For omni_*.mk:"
    echo "  PRODUCT_DEVICE := $(get_prop ro.product.device)"
    echo "  PRODUCT_NAME := omni_$(get_prop ro.product.device)"
    echo "  PRODUCT_BRAND := $(get_prop ro.product.brand)"
    echo "  PRODUCT_MODEL := $(get_prop ro.product.model)"
    echo "  PRODUCT_MANUFACTURER := $(get_prop ro.product.manufacturer)"
    echo ""
    echo "Screen Configuration:"
    RESOLUTION=$(safe_exec "wm size" | grep -E "(Physical size|Override size)" | head -n1 | cut -d':' -f2 | tr -d ' ')
    if [ -z "$RESOLUTION" ]; then
        RESOLUTION=$(safe_exec "wm size" | tail -n1 | tr -d ' ')
    fi
    echo "  Resolution: $RESOLUTION"
    if [[ "$RESOLUTION" == *"1080x"* ]] || [[ "$RESOLUTION" == *"x1080"* ]]; then
        echo "  Recommended TW_THEME: portrait_hdpi or landscape_hdpi"
    elif [[ "$RESOLUTION" == *"720x"* ]] || [[ "$RESOLUTION" == *"x720"* ]]; then
        echo "  Recommended TW_THEME: portrait_mdpi or landscape_mdpi"
    fi
    echo ""
    echo "Next Steps:"
    echo "  1. Extract boot.img from device"
    echo "  2. Analyze boot.img with: abootimg -i boot.img"
    echo "  3. Create device tree using examples/device_tree_sample/"
    echo "  4. See docs/TWRP_BUILDING_GUIDE.md for complete instructions"
    echo ""
} | tee -a "$OUTPUT_FILE"

# Complete
echo "" | tee -a "$OUTPUT_FILE"
echo "========================================" | tee -a "$OUTPUT_FILE"
echo "  INFORMATION EXTRACTION COMPLETE" | tee -a "$OUTPUT_FILE"
echo "========================================" | tee -a "$OUTPUT_FILE"

print_success "Device information saved to: $OUTPUT_FILE"
echo ""
print_info "Additional steps:"
echo "  1. Review the output file"
echo "  2. Extract boot.img from your device"
echo "  3. Analyze boot.img using: abootimg -i boot.img"
echo "  4. Refer to docs/TWRP_BUILDING_GUIDE.md for next steps"
echo ""
print_info "For online building, visit: https://www.hovatek.com/twrpbuilder/"
echo ""
